import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/registry";
import NextThemeProvider from "@/styles/NextThemeProvider";
import { Inter } from "next/font/google";
import { ToastContainer } from "@/components/Toast";
import { TabBottom } from "@/components/TabBottom";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="pt-br">
            <body className={inter.className}>
                <StyledComponentsRegistry>
                    <NextThemeProvider>
                        <ToastContainer />
                        <TabBottom notRender={["/Temp"]} />
                        {children}
                    </NextThemeProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
